{
 "title": "A dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Transfers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Transfers In per User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irods_transfers_per_user{direction=\"in\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Transfers Out per User",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irods_transfers_per_user{direction=\"out\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  { "title": "Zone", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Total Users",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_users", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total rodsadmins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_rodsadmins", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total groupadmins",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_groupadmins", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total rodsgroups",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_rodsgroups", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total rodsusers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_rodsusers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Collections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_collections", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Objects",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_objects", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas", "legendFormat": "__auto" }
   ]
  },
  { "title": "Checksums", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Good Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_good", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stale Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_stale", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Intermediate Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_intermediate", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Locked Replicas",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_locked", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Replicas without Checksums",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "irods_replicas_without_checksums",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicas with Checksums",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_with_checksums", "legendFormat": "__auto" }
   ]
  },
  { "title": "Trash", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Bytes in Trash",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_bytes_in_trash", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Collections in Trash",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_collections_in_trash", "legendFormat": "{{resc_name}}" }
   ]
  },
  {
   "title": "Objects in Trash",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_objects_in_trash", "legendFormat": "{{resc_name}}" }
   ]
  },
  {
   "title": "Replicas in Trash",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_in_trash", "legendFormat": "{{resc_name}}" }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Bytes per Resource",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_bytes_per_resource", "legendFormat": "{{resc_name}}" }
   ]
  },
  {
   "title": "Replicas per Resource",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "irods_replicas_per_resource", "legendFormat": "{{resc_name}}" }
   ]
  },
  { "title": "Owner", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Bytes per Owner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "irods_bytes_per_owner", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Collections per Owner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 34 },
   "targets": [
    { "expr": "irods_collections_per_owner", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Objects per Owner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 34 },
   "targets": [
    { "expr": "irods_objects_per_owner", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Replicas per Owner",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 34 },
   "targets": [
    { "expr": "irods_replicas_per_owner", "legendFormat": "{{user_name}}" }
   ]
  },
  {
   "title": "Database Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "database_connection_count", "legendFormat": "__auto" }
   ]
  }
 ]
}